Add Update Progress Indicator
elementary/settings-daemon pull request #173
Opened 2024-12-16 12:57 UTC by alainm23

2024-12-16 18:21 UTC, stsdc approved these changes

2024-12-16 18:54 UTC, leolost2605 requested changes

2024-12-16 18:54 UTC, leolost2605 commented on src/Backends/SystemUpdate.vala
> +        update_state (current_state.state, PkUtils.status_to_title (progress.status),
If you have to split arguments into lines, a new line for every argument is preferred, see https://docs.elementary.io/develop/writing-apps/code-style#splitting-arguments-into-lines

2024-12-16 18:54 UTC, leolost2605 commented on src/Backends/SystemUpdate.vala
> +    private void update_state (PkUtils.State state, string message = "",
Same here

2024-12-16 18:54 UTC, leolost2605 commented on src/Backends/UbuntuDrivers.vala
> +        update_state (current_state.state, PkUtils.status_to_title (progress.status),
And here

2024-12-16 18:54 UTC, leolost2605 commented on src/Backends/UbuntuDrivers.vala
> +        uint percentage = 0, uint64 download_size_remaining = 0) {
And here

2024-12-17 15:01 UTC, leolost2605 approved these changes
LGTM

2024-12-17 15:11 UTC, merged